=== jsbentle/Exercise2/JobPosting.dtd
<!DOCTYPE job-posting
  [<!ELEMENT job-posting (
    <!ELEMENT posting-information (job-details, duties, qualifications)>
      <!ELEMENT job-details (list)>
        <!ELEMENT list (item)*>
        <!ELEMENT item (#PCDATA | posting-number | internal-recruitment | working-title | hiring-range | work-schedule | job-location | department)*>
      <!ELEMENT posting-number (#PCDATA)>
      <!ELEMENT internal-recruitment (#PCDATA)>
      <!ELEMENT working-title (#PCDATA)>
      <!ELEMENT hiring-range (#PCDATA)>
      <!ELEMENT work-schedule (#PCDATA)>
      <!ELEMENT job-location (#PCDATA)>
      <!ELEMENT department (#PCDATA)>
      <!ELEMENT essential-job-duties (#PCDATA)>
      <!ELEMENT other-responsibilities (#PCDATA)>
    <!ELEMENT qualifications (education, required, preferred, licences)>
      <!ELEMENT education (hs | bs | mams | phd)>
        <!ELEMENT hs (#PCDATA)>
        <!ELEMENT bs (#PCDATA)>
        <!ELEMENT mams (#PCDATA)>
        <!ELEMENT phd (#PCDATA)>
      <!ELEMENT required (#PCDATA)>
      <!ELEMENT preferred (#PCDATA)>
      <!ELEMENT licences (EMPTY)>
    <!ELEMENT dates ()>
       <!ELEMENT posted (#PCDATA)>
       <!ELEMENT closed (#PCDATA)>

=== jsbentle/Exercise2/stewardshipofficer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="stylesheet.css"?>
<!DOCTYPE job-posting SYSTEM "JobPosting.dtd">
  <job-posting> 
    <posting-information> 
      <job-details> 
        <list> 
            <item><working-title>Title: Stewardship Officer</working-title></item>  
            <item><posting-number>ID: 1234567</posting-number></item>  
            <item><internal-recruitment>Internal Recruitment: No</internal-recruitment></item>  
            <item><hiring-rang>Salary Range: $51,000-$60,000</hiring-rang></item>  
            <item><work-schedule>Work Schedule: M-F 8a - 5p</work-schedule></item>  
            <item><job-location>Work Location: Raleigh,NC</job-location></item>  
            <item><department>Department: University Advancement</department></item>  
         </list>  
      </job-details>
      <duties>
        <list 2>
            <item2>The essential functions of this position include administering the leadership acknowledgment process, leading tailored stewardship and recognition strategies for select donors, and advising on annual stewardship priorities and special projects. Additionally, the role advances universitywide initiatives like campaign stewardship, Day of Giving, and Pack Appreciation Day, coordinates special-day donor communications, serves as a liaison for endowment reports, maintains accurate donor records, and stays aligned with emerging industry trends and best practices.</item2>
        </list 2>
      </duties>
      <qualifications>
        
      </qualifications>
    </posting-information>
  </job-posting>
